### ISSUE TITLE
cicd

### ISSUE THREAD

**Issue by FelixStarship** [yangshun2005/gitlab-cicd#1]
1.你好问下gitlab runner宿主机需要有docker环境runner才能执行.gtilab-ci.yml里面的docker命令对嘛？
2.runner需要把gitlab的代码git pull到runner宿主机才能执行job嘛？
3.看你代码dockerfile里面的$GOPATH环境变量，如果代码推到gitlab上这个路径怎么读取，在本机我可以理解，是本机的工作目录，如果gitlab制品仓库，这个路径怎么读取

**Comment by yangshun2005** [comment]
1.runner可以在docker上运行，也可以在systemd上运行
2.是的.看gitlab的yaml
3.$GOPATH及相关环境env是以runner所在OS确认
